spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    # 开发禁用缓存
    cache: false
  application:
    name: server1
  datasource:
    url: jdbc:mysql://localhost:3306/server1?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
    # driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
#mybatis:
#  mapperLocations: classpath:com/boot/mapper/*.xml
#  typeAliasesPackage: cn.boot.domain
# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
#logging:
#  level:
#    root: info
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka #告诉服务提供者要把服务注册到哪儿